#!/bin/bash
#


#bq load --quote=" " --skip_leading_rows=1 --field_delimiter='\t' test.b ../data/matchedVideo20160510  id:integer,company_id:integer,trackingMeta_id:integer,trackingWebsite_id:integer,key_id:string,relationGroup_id:integer,view_count:integer,poster:string,post_date:timestamp,relationGroup_status:string,is_contentRule_applied:string,is_snapshot_generated:string,is_in_takedown_queue:string,is_media_file_exist:string,in_takedown_queue_date:timestamp,count_send_notice:integer,first_send_notice_date:timestamp,last_send_notice_date:timestamp,notice_send_by:string,takeoff_time:timestamp,content_type:string,content_sub_type:string,takeoff_type:string,hide_flag:integer,hide_by:string,hide_date:timestamp,clip_duration:integer,clip_size:integer,clip_url_reverse:string,clip_url:string,download_url:string,clip_title:string,clip_offset:integer,meta_offset:integer,score_video:integer,score_audio:integer,matched_duration:integer,matched_video_duration:integer,matched_audio_duration:integer,verification:string,posterID_url:string,matched_storage_domain:string,matched_storage_date:string,season_number:integer,episode_number:integer,instance_title:string,instance_duration:integer,matchedFile_id:integer,meta_uuid:string,meta_title:string,meta_duration:integer,vddb_title:string,notes:string,start_at:timestamp,created_at:timestamp,updated_at:timestamp,contributor:string,is_poster_whitelist_filtered:string,last_refresh_at:timestamp

#bq load --quote=" " --skip_leading_rows=1 --field_delimiter='\t' test.c ../data/matchedVideo20160511 id,company_id,trackingMeta_id,trackingWebsite_id,key_id,relationGroup_id,view_count,poster,post_date,relationGroup_status,is_contentRule_applied,is_snapshot_generated,is_in_takedown_queue,is_media_file_exist,in_takedown_queue_date,count_send_notice,first_send_notice_date,last_send_notice_date,notice_send_by,takeoff_time,content_type,content_sub_type,takeoff_type,hide_flag,hide_by,hide_date,clip_duration,clip_size,clip_url_reverse,clip_url,download_url,clip_title,clip_offset,meta_offset,score_video,score_audio,matched_duration,matched_video_duration,matched_audio_duration,verification,posterID_url,matched_storage_domain,matched_storage_date,season_number,episode_number,instance_title,instance_duration,matchedFile_id,meta_uuid,meta_title,meta_duration,vddb_title,notes,start_at,created_at,updated_at,contributor,is_poster_whitelist_filtered,last_refresh_at

#bq load --quote= --skip_leading_rows=1 --field_delimiter='\t' test.c ../data/matchedVideo20160511
bq load --source_format="CSV" --quote="v" --skip_leading_rows=1 --field_delimiter="\t" test.c ../data/a id:INTEGER,company_id:INTEGER,trackingMeta_id:INTEGER,trackingWebsite_id:INTEGER,key_id:STRING,relationGroup_id:INTEGER,view_count:INTEGER,poster:STRING,post_date:STRING,relationGroup_status:STRING,is_contentRule_applied:STRING,is_snapshot_generated:STRING,is_in_takedown_queue:STRING,is_media_file_exist:STRING,in_takedown_queue_date:STRING,count_send_notice:INTEGER,first_send_notice_date:STRING,last_send_notice_date:STRING,notice_send_by:STRING,takeoff_time:STRING,content_type:STRING,content_sub_type:STRING,takeoff_type:STRING,hide_flag:STRING,hide_by:STRING,hide_date:STRING,clip_duration:INTEGER,clip_size:INTEGER,clip_url_reverse:STRING,clip_url:STRING,download_url:STRING,clip_title:STRING,clip_offset:INTEGER,meta_offset:INTEGER,score_video:STRING,score_audio:STRING,matched_duration:INTEGER,matched_video_duration:INTEGER,matched_audio_duration:INTEGER,verification:STRING,posterID_url:STRING,matched_storage_domain:STRING,matched_storage_date:STRING,season_number:STRING,episode_number:STRING,instance_title:STRING,instance_duration:INTEGER,matchedFile_id:INTEGER,meta_uuid:STRING,meta_title:STRING,meta_duration:INTEGER,vddb_title:STRING,notes:STRING,start_at:STRING,created_at:STRING,updated_at:STRING,contributor:STRING,is_poster_whitelist_filtered:STRING,last_refresh_at:STRING
