#!/bin/bash
#Date: 2015-11-6
#Desc: update hostCountry where host country of sites are missing in table SiteDetail_Monthly and SiteDetail_Yearly

mysql_conf_114="mysql -h192.168.110.114 -ukettle -pk3UTLe DM_VIACOM " 
last_month=`date -d "now 1 month ago" +%Y-%m`

#######update host country where host country of sites are missing in table SiteDetail_Monthly and SiteDetail_Yearly
${mysql_conf_114} -e "update SiteDetail_Monthly set HostCountry = 'Luxembourg' where websiteName = 'inwarez.org';update SiteDetail_Monthly set HostCountry = 'Netherlands' where websiteName = 'hugoclab.ru'; update SiteDetail_Monthly set HostCountry = 'Netherlands' where websiteName = 'torrentreactor'; update SiteDetail_Monthly set HostCountry = 'Ukraine' where websiteName = 'sumotorrent'; update SiteDetail_Monthly set HostCountry = 'Netherlands' where websiteName = 'Bts'; update SiteDetail_Monthly set HostCountry = 'Netherlands' where websiteName = 'serietvsubita.net'; update SiteDetail_Monthly set HostCountry = 'Sweden' where websiteName = 'serietvsubita.net'; update SiteDetail_Monthly set HostCountry = 'Ukraine' where websiteName = 'seedpeer'; update SiteDetail_Yearly set HostCountry = 'Luxembourg' where websiteName = 'inwarez.org'; update SiteDetail_Yearly set HostCountry = 'Netherlands' where websiteName = 'hugoclab.ru'; update SiteDetail_Yearly set HostCountry = 'Netherlands' where websiteName = 'torrentreactor'; update SiteDetail_Yearly set HostCountry = 'Ukraine' where websiteName = 'sumotorrent'; update SiteDetail_Yearly set HostCountry = 'Netherlands' where websiteName = 'Bts'; update SiteDetail_Yearly set HostCountry = 'Netherlands' where websiteName = 'serietvsubita.net'; update SiteDetail_Yearly set HostCountry = 'Sweden' where websiteName = 'serietvsubita.net'; update SiteDetail_Yearly set HostCountry = 'Ukraine' where websiteName = 'seedpeer';"


######update country   et first  letter capital
${mysql_conf_114} -e "update SiteDetail_Yearly set HostCountry = CONCAT(UCASE(left(HostCountry, 1)), LCASE(MID(HostCountry, 2, char_length(HostCountry)-1))) where YM = '${last_month}';update SiteDetail_Yearly set HostCountry ='Moldova' where YM = '${last_month}' and HostCountry = 'MOLDOVA, REPUBLIC OF'; update SiteDetail_Yearly set HostCountry ='United States' where YM = '${last_month}' and HostCountry = 'UNITED STATES'; update SiteDetail_Yearly set HostCountry = 'United Kingdom' where YM = '${last_month}' and HostCountry = 'UNITED KINGDOM'; update SiteDetail_Yearly set HostCountry = 'Costa Rica' where YM = '${last_month}' and HostCountry = 'Costa Rica';  update SiteDetail_Monthly set HostCountry = CONCAT(UCASE(left(HostCountry, 1)), LCASE(MID(HostCountry, 2, char_length(HostCountry)-1))) where YM = '${last_month}';update SiteDetail_Monthly set HostCountry = 'Moldova' where YM = '${last_month}' and HostCountry = 'MOLDOVA, REPUBLIC OF'; update SiteDetail_Monthly set HostCountry = 'United States' where YM = '${last_month}' and HostCountry = 'UNITED STATES'; update SiteDetail_Monthly set HostCountry = 'United Kingdom' where YM = '${last_month}' and HostCountry = 'UNITED KINGDOM'; update P2PISPSUM_Monthly set Country = CONCAT(UCASE(left(Country, 1)), LCASE(MID(Country, 2, char_length(Country)-1))) where YM = '${last_month}'; update P2PISPSUM_Monthly set Country = 'Moldova' where YM = '${last_month}' and Country = 'MOLDOVA, REPUBLIC OF'; update P2PISPSUM_Monthly set Country = 'United States' where YM = '${last_month}' and Country = 'UNITED STATES'; update P2PISPSUM_Monthly set Country = 'United Kingdom' where YM = '${last_month}' and Country = 'UNITED KINGDOM'; update SiteDetail_Yearly set HostCountry = 'Costa Rica' where YM = '${last_month}' and HostCountry = 'Costa Rica'; update P2PISPSUM_Yearly set Country = CONCAT(UCASE(left(Country, 1)), LCASE(MID(Country, 2, char_length(Country)-1))) where YM = '${last_month}'; update P2PISPSUM_Yearly set Country = 'Moldova' where YM = '${last_month}' and Country = 'MOLDOVA, REPUBLIC OF'; update P2PISPSUM_Yearly set Country = 'United States' where YM = '${last_month}' and Country = 'UNITED STATES'; update P2PISPSUM_Yearly set Country = 'United Kingdom' where YM = '${last_month}' and Country = 'UNITED KINGDOM';"

#host country set '' = '-'
${mysql_conf_114} -e "update SiteDetail_Yearly set HostCountry ='-' where HostCountry='';update SiteDetail_Monthly set HostCountry ='-' where HostCountry='';"
